const APIV1 = '/api/v1'


module.exports = {
  name: '管理后台',
  prefix: 'antdAdmin',
  footerText: '管理后台  © 2017',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  YQL: [],
  CORS: [],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: `${APIV1}/user/login`,
    userLogout: `${APIV1}/user/logout`,
    userInfo: `${APIV1}/userInfo`,
    users: `${APIV1}/users`,
    posts: `${APIV1}/posts`,
    user: `${APIV1}/user/:id`,
    dashboard: `${APIV1}/dashboard`,
    menus: `${APIV1}/menus`,
    settingRole: `${APIV1}/settingRole`,
    settingPermission: `${APIV1}/settingPermission/:id`,
    merchantManage: `${APIV1}/merchantManage/:id`,
    userManage: `${APIV1}/userManage/:id`,
    payOrder: `${APIV1}/payOrder/:id`,
    profitOrder: `${APIV1}/profitOrder/:id`,
    profitManage: `${APIV1}/profitManage`,
    withdrawOrder: `${APIV1}/withdrawOrder/:id`,
    withdrawRecord: `${APIV1}/withdrawRecord/:id`,
    notWithdrawOrder: `${APIV1}/notWithdrawOrder/:id`,
    qrcodeList: `${APIV1}/qrcodeList/:id`,
    qrcodeApply: `${APIV1}/qrcodeApply`,
    remit: `${APIV1}/remit/:id`,
    flowUser: `${APIV1}/flowUser`,
    flowFinance: `${APIV1}/flowFinance`,
    flowFinanceOrder: `${APIV1}/flowFinanceOrder`,
    flowOrder: `${APIV1}/flowOrder`,
    cashierInfo: `${APIV1}/cashierInfo`,
    downloadFile: `${APIV1}/downloadFile`,
  },
}
