const APIV1 = '/api/v1'
const APIV2 = '/api/v2'

module.exports = {
  name: '  阅微管理后台',
  prefix: 'antdAdmin',
  footerText: '阅微管理后台  © 2017',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: [],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: `${APIV1}/user/login`,
    userLogout: `${APIV1}/user/logout`,
    userInfo: `${APIV1}/userInfo`,
    users: `${APIV1}/users`,
    posts: `${APIV1}/posts`,
    user: `${APIV1}/user/:id`,
    dashboard: `${APIV1}/dashboard`,
    menus: `${APIV1}/menus`,
    merchantInfo: `${APIV1}/merchantInfo`,
    merchantKey: `${APIV1}/merchantKey`,
    merchantBank: `${APIV1}/merchantBank`,
    merchantRate:`${APIV1}/merchantRate`,
    payOrder: `${APIV1}/payOrder`,
    withdrawOrder: `${APIV1}/withdrawOrder`,
    notWithdrawOrder: `${APIV1}/notWithdrawOrder`,
    remit: `${APIV1}/remit/:id`,
    flowUser: `${APIV1}/flowUser`,
    flowFinance:  `${APIV1}/flowFinance`,
    flowFinanceOrder: `${APIV1}/flowFinanceOrder`,
    flowOrder: `${APIV1}/flowOrder`,
    cashierInfo:`${APIV1}/cashierInfo`,
  },
}
